### ISSUE TITLE
Had to manually create default dir

### ISSUE THREAD

**Issue by BlakeLeBlancGuernsey** [neo451/feed.nvim#27]
On Windows, after installing the plugin, executing `Feed` returned the following error:

```
Error executing Lua callback: ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:511:
FileNotFoundError stack traceback:
[C]: in function 'error'
...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:511: in function 'mkdir'
...c/AppData/Local/nvim-data/lazy/feed.nvim/lua/feed/db.lua:123: in function 'prepare_db'
...c/AppData/Local/nvim-data/lazy/feed.nvim/lua/feed/db.lua:144: in function
<...c/AppData/Local/nvim-data/lazy/feed.nvim/lua/feed/db.lua:141>
...pData/Local/nvim-data/lazy/feed.nvim/lua/feed/render.lua:15: in main chunk
[C]: in function 'require'
...lanc/AppData/Local/nvim-data/lazy/feed.nvim/lua/feed.lua:4: in function
<...lanc/AppData/Local/nvim-data/lazy/feed.nvim/lua/feed.lua:3>   

```

The fix was to manually create the default directory:
```
> mkdir ~/.local/share/nvim/feed/
```

Bad idea to add this step to the readme?

Thanks for a cool plugin! :)

**Comment by neo451** [comment]
Upon further look, it was just a small bug in file path checking. No need to manually create now.

I also updated a the default path to the more idiomatic neovim's standard data path. You can get a update to see if it works, after update you can run `Feed blowup` to rm the old dir, and reenter neovim and start using the new dir. or just mv the directory.

**Comment by BlakeLeBlancGuernsey** [comment]
Cool! Nice one @neo451 !
