### ISSUE TITLE
only support lua5.1?

### ISSUE THREAD

**Issue by cxwx** [neo451/feed.nvim#80]
  Error  16:40:44 notify.error lazy.nvim Failed to run `config` for feed.nvim

...xu/.local/share/nvim/lazy/feed.nvim/lua/feed/db/init.lua:2: module 'pathlib' not found:
	no field package.preload['pathlib']
cache_loader: module pathlib not found
cache_loader_lib: module pathlib not found
	no file './pathlib.lua'
	no file '/opt/homebrew/share/luajit-2.1/pathlib.lua'
	no file '/usr/local/share/lua/5.1/pathlib.lua'
	no file '/usr/local/share/lua/5.1/pathlib/init.lua'
	no file '/opt/homebrew/share/lua/5.1/pathlib.lua'
	no file '/opt/homebrew/share/lua/5.1/pathlib/init.lua'
	no file '/Users/XX/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/pathlib.lua'
	no file '/Users/XX/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/pathlib/init.lua'
	no file './pathlib.so'
	no file '/usr/local/lib/lua/5.1/pathlib.so'
	no file '/opt/homebrew/lib/lua/5.1/pathlib.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/XX/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/pathlib.so'

# stacktrace:
  - /feed.nvim/lua/feed/db/init.lua:2
  - /feed.nvim/lua/feed/utils.lua:180 _in_ **__index**
  - /feed.nvim/lua/feed/fetch.lua:12
  - /feed.nvim/lua/feed/commands.lua:5
  - /feed.nvim/lua/feed.lua:7 _in_ **setup**
  - ~/cx_rc/config/nvim/init.lua:53
   Info  16:41:49 notify.info url-open Opening https://github.com/neo451/feed.nvim

**Comment by neo451** [comment]
Just try update, I forgot to add the dependency on a previous release, but it should be fixed and working now.

**Comment by cxwx** [comment]
solved now
