### ISSUE TITLE
Show only one feed source?

### ISSUE THREAD

**Issue by rodhash** [neo451/feed.nvim#91]
When I run `Feed show_index` it displays all my RSS sources, can we display only one? Or perhaps filter just one source?

Thanks.

**Comment by neo451** [comment]
you can use query DSL to get only a certain feed, so if you want the feed with name neovim you can just query `=neovim`, and there are a number of ways you can do this:
1. in vim commandline, just type `Feed =neovim`
2. in the FeedIndex page, press `s` and enter the query.
3. in anywhere, use `Feed search` to open telescope/mini.pick and type in the query

guess the docs are still very incomplete and needs attention, thank you for feedback

**Comment by rodhash** [comment]
Yeah actually I tried the search feature but it'll search and display the feeds / news that match my search string, right?

What I mean is, let's say I have multiple RSS added in `setup.feeds` .. for example:
```lua
      require"feed".setup{
        feeds = {
          -- tags given to a feed to be tagged to all its entries
          { "https://neovim.io/news.xml", name = "Neovim News", tags = { "tech", "news" } },
          -- RssHub link is also a first class citizen like http/https
          -- rsshub://{route} will be the unique identifier in the database and resolved when fetching feeds which instance to use base on your config.rsshub_instance
          "rsshub://apnews/topics/apf-topnews",
          -- "opera://news/?preview_title=República&preview_url=https%3A%2F%2Fwww.gazetadopovo.com.br%2Ffeed%2Frss%2Frepublica.xml",
          {"https://www.gazetadopovo.com.br/feed/rss/republica.xml", name = "Gazeta: republica", tags = {"news"}},
         }
       }
```

When I open feed I'll have all of them being displayed, like this:

<img width="225" alt="image" src="https://github.com/user-attachments/assets/8e9d2a0e-bdb6-4343-baef-35b44f0d6258">

Rationale: Sometimes it might be interesting to see only local news instead of all of them at once. Or, might be interesting to see only financial news.. something like this.

Is there a filter feature for this? I couldn't find it, and in my tests the search feature doesn't seem to accept a source name.


Thanks.

**Comment by rodhash** [comment]
ie: when I open newsboat I have the option to choose which source I want to read:

<img width="601" alt="image" src="https://github.com/user-attachments/assets/9c5f1b99-1dce-4fb0-b12d-58f9d3c6e12c">

**Comment by neo451** [comment]
yes filter by source is supported, and the search feature is not only simple regex match
see here: https://github.com/neo451/feed.nvim/wiki/Usage-Guide#feed-searching
it is from elfeed's query grammar, see elfeed's explaination: https://github.com/skeeto/elfeed#filter-syntax
`=neovim` gives you only this feed's entries, `+news` gives you all entries with the tag

**Comment by rodhash** [comment]
Thank you, that's it.
